spring:
  application:
    name: exposed-example
  datasource:
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true # Java 21 virtual threads ??
  exposed:
    show-sql: true

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/kim_wonung
    username: kimwonung
    password: kimwonung

server.port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/kim_wonung
    username: kimwonung
    password: kimwonung

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: TBD
    username: TBD
    password: TBD
